---
title: "decision-trees"
author: "Shivam Sawhney"
date: "2023-03-10"
output: html_document
---

```{r warning=FALSE}

# Loading package
library(tree)
library(caTools)
library(ggplot2)
library(dplyr)
library(gridExtra)
'%notin%' <- Negate('%in%')
theme_set(theme_bw(base_size = 16))
library(readr)
library(rpart)
library(caret)
library(rpart.plot)

```

```{r warnings=FALSE}

#Data Cleaning and Prep

d1 <- read_csv("Premier-League-Squad-Playing-Time.csv",  show_col_types = FALSE)
d2 <- read_csv("La-Liga-Squad-Playing-Time.csv",  show_col_types = FALSE)
d3 <- read_csv("Bundesliga-Squad-Playing-Time.csv", show_col_types = FALSE)
d4 <- read_csv("Ligue-1-Squad-Playing-Time.csv", show_col_types = FALSE)
d5 <- read_csv("Serie-A-Squad-Playing-Time.csv", show_col_types = FALSE)

dm1 <- d1[c(2:19, 24)]
dm1 <- dm1[-c(1,6,7)]
dm2 <- d2[c(2:19, 24)]
dm2 <- dm2[-c(1,6,7)]
dm3 <- d3[c(2:19, 24)]
dm3 <- dm3[-c(1,6,7)]
dm4 <- d4[c(2:19, 24)]
dm4 <- dm4[-c(1,6,7)]
dm5 <- d5[c(2:19, 24)]
dm5 <- dm5[-c(1,6,7)]

dm1$`Team Success (xG) xG+/-90` <- ifelse(dm1$`Team Success (xG) xG+/-90`>0,"Positive", "Negative")
dm1$`Team Success (xG) xG+/-90` <- as.factor(dm1$`Team Success (xG) xG+/-90`)

dm2$`Team Success (xG) xG+/-90` <- ifelse(dm2$`Team Success (xG) xG+/-90`>0,"Positive", "Negative")
dm2$`Team Success (xG) xG+/-90` <- as.factor(dm2$`Team Success (xG) xG+/-90`)

dm3$`Team Success (xG) xG+/-90` <- ifelse(dm3$`Team Success (xG) xG+/-90`>0,"Positive", "Negative")
dm3$`Team Success (xG) xG+/-90` <- as.factor(dm3$`Team Success (xG) xG+/-90`)

dm4$`Team Success (xG) xG+/-90` <- ifelse(dm4$`Team Success (xG) xG+/-90`>0,"Positive", "Negative")
dm4$`Team Success (xG) xG+/-90` <- as.factor(dm4$`Team Success (xG) xG+/-90`)

dm5$`Team Success (xG) xG+/-90` <- ifelse(dm5$`Team Success (xG) xG+/-90`>0,"Positive", "Negative")
dm5$`Team Success (xG) xG+/-90` <- as.factor(dm5$`Team Success (xG) xG+/-90`)


dm1 <- dm1[-c(12:15)]
dm2 <- dm2[-c(12:15)]
dm3 <- dm3[-c(12:15)]
dm4 <- dm4[-c(12:15)]
dm5 <- dm5[-c(12:15)]

df <- as.data.frame(rbind(dm1,dm2,dm3,dm4,dm5)) 

```


```{r}

# Splitting data into train and test data

split <- sample.split(df, SplitRatio = 0.9)
train_cl <- subset(df, split == "TRUE")
test_cl <- subset(df, split == "FALSE")

# Exporting Samples of Testing and Training sets

write.csv(train_cl, "C:\\Users\\shiva\\OneDrive\\Documents\\Sem 2 - MS\\CSCI 5622-072 Machine Learning\\Final Project\\Sample_Training_Set_DT.csv")

write.csv(test_cl, "C:\\Users\\shiva\\OneDrive\\Documents\\Sem 2 - MS\\CSCI 5622-072 Machine Learning\\Final Project\\Sample_Testing_Set_DT.csv")

```

```{r}

#Implementing DT

model <- rpart(`Team Success (xG) xG+/-90` ~. , data = train_cl)
plot(model, margin=0.05)
text(model, cex = 0.9)

```


```{r}

#Making Predictions

pr <- predict(model, newdata = train_cl, type="class")

```

```{r}

#Confusion matrix and accuracy

confusionMatrix(table(pred = pr, true = train_cl$`Team Success (xG) xG+/-90`))

```


```{r}
#Visualizations

pruned_tree <- prune.rpart(model, cp=0)

#plot the pruned tree

prp(pruned_tree, faclen=0, extra=1,digits=5)

```

```{r}
#Better Viz

rpart.plot(model, box.palette="RdGn", shadow.col="gray", nn=TRUE)

```

```{r}

#DT - 2 With the same sequence of steps as DT 1

dd1 <-read_csv("Premier-League-Possession.csv", show_col_types = FALSE)
dd2 <- read_csv("La-Liga-Possession.csv",  show_col_types = FALSE)
dd3 <- read_csv("Bundesliga-Possession.csv", show_col_types = FALSE)
dd4 <- read_csv("Ligue-1-Possession.csv", show_col_types = FALSE)
dd5 <- read_csv("Serie-A-Possession.csv", show_col_types = FALSE)
dd1 <- dd1[-c(1)]
dd2 <- dd2[-c(1)]
dd4 <- dd4[-c(1)]
dd5 <- dd5[-c(1)]

names <- c( "Squad","Pl"	, "Poss"	 ,"Full_Game",	"Touches","Def_Pen","Def_3rd","Mid_3rd"	,"Att_3rd",	"Att_Pen","Live",	"Take-Ons-Att", "Succ",	"Succ%", "Tkld", "Tkld%", "Carries","TotDist"	, "PrgDist", "PrgC",	"One-Third",	"CPA",	 "Mis",	 "Dis", "Rec",	 "PrgR",	"Season")

colnames(dd1) <- names
colnames(dd2) <- names
colnames(dd3) <- names
colnames(dd4) <- names
colnames(dd5) <- names

dd1 <- dd1[-c(1,4,11,17:27)]
dd2 <- dd2[-c(1,4,11,17:27)]
dd3 <- dd3[-c(1,4,11,17:27)]
dd4 <- dd4[-c(1,4,11,17:27)]
dd5 <- dd5[-c(1,4,11,17:27)]

dd1$Att_Tch <- as.numeric((dd1$Att_3rd + dd1$Att_Pen)/(dd1$Touches)*100)
dd1$Att_Tch <- ifelse(dd1$Att_Tch>27.8, "More than average", "Less than average")
dd1$Att_Tch <- as.factor(dd1$Att_Tch)
dd2$Att_Tch <- as.numeric((dd2$Att_3rd + dd2$Att_Pen)/(dd2$Touches)*100)
dd2$Att_Tch <- ifelse(dd2$Att_Tch>27.3, "More than average", "Less than average")
dd2$Att_Tch <- as.factor(dd2$Att_Tch)
dd3$Att_Tch <- as.numeric((dd3$Att_3rd + dd3$Att_Pen)/(dd3$Touches)*100)
dd3$Att_Tch <- ifelse(dd3$Att_Tch>25, "More than average", "Less than average")
dd3$Att_Tch <- as.factor(dd3$Att_Tch)
dd4$Att_Tch <- as.numeric((dd4$Att_3rd + dd4$Att_Pen)/(dd4$Touches)*100)
dd4$Att_Tch <- ifelse(dd4$Att_Tch>25, "More than average", "Less than average")
dd4$Att_Tch <- as.factor(dd4$Att_Tch)
dd5$Att_Tch <- as.numeric((dd5$Att_3rd + dd5$Att_Pen)/(dd5$Touches)*100)
dd5$Att_Tch <- ifelse(dd5$Att_Tch>27, "More than average", "Less than average")
dd5$Att_Tch <- as.factor(dd5$Att_Tch)

df_2 <- as.data.frame(rbind(dd1,dd2,dd3,dd4,dd5))

```

```{r}

# Splitting data into train and test data

split_2 <- sample.split(df_2, SplitRatio = 0.9)
train_cl_2 <- subset(df_2, split_2 == "TRUE")
test_cl_2 <- subset(df_2, split_2 == "FALSE")

```

```{r}

#Implementing DT

model_2 <- rpart(Att_Tch ~. , data = train_cl_2)

```


```{r}

#Making Predictions

pr_2 <- predict(model_2, newdata = train_cl_2, type="class")

```

```{r}

#Confusion Matrix and Accuracy

confusionMatrix(table(pred = pr_2, true = train_cl_2$Att_Tch))

```

```{r}

#Visualizations

pruned_tree_2 <- prune.rpart(model_2, cp=0)

#plot the pruned tree

prp(pruned_tree_2, faclen=0, extra=1,digits=5)

```

```{r}

#Better Viz

rpart.plot(model_2, box.palette="RdGn", shadow.col="gray", nn=TRUE)

```

```{r}

#Implementing DT 3

dd1 <-read_csv("Premier-League-Possession.csv", show_col_types = FALSE)
dd2 <- read_csv("La-Liga-Possession.csv",  show_col_types = FALSE)
dd3 <- read_csv("Bundesliga-Possession.csv", show_col_types = FALSE)
dd4 <- read_csv("Ligue-1-Possession.csv", show_col_types = FALSE)
dd5 <- read_csv("Serie-A-Possession.csv", show_col_types = FALSE)
dd1 <- dd1[-c(1)]
dd2 <- dd2[-c(1)]
dd4 <- dd4[-c(1)]
dd5 <- dd5[-c(1)]

names <- c( "Squad","Pl"	, "Poss"	 ,"Full_Game",	"Touches","Def_Pen","Def_3rd","Mid_3rd"	,"Att_3rd",	"Att_Pen","Live",	"Take-Ons-Att", "Succ",	"Succ%", "Tkld", "Tkld%", "Carries","TotDist"	, "PrgDist", "PrgC",	"One-Third",	"CPA",	 "Mis",	 "Dis", "Rec",	 "PrgR",	"Season")

colnames(dd1) <- names
colnames(dd2) <- names
colnames(dd3) <- names
colnames(dd4) <- names
colnames(dd5) <- names

dd1 <- dd1[-c(1,2,27)]
dd2 <- dd2[-c(1,2,27)]
dd3 <- dd3[-c(1,2,27)]
dd4 <- dd4[-c(1,2,27)]
dd5 <- dd5[-c(1,2,27)]

dd1$Att_Car <- as.numeric((dd1$`One-Third` + dd1$CPA)/(dd1$Carries)*100)
dd1$Att_Car <- ifelse(dd1$Att_Car>5.3, "More than average", "Less than average")
dd1$Att_Car <- as.factor(dd1$Att_Car)
dd2$Att_Car <- as.numeric((dd2$`One-Third` + dd2$CPA)/(dd2$Carries)*100)
dd2$Att_Car <- ifelse(dd2$Att_Car>5.3, "More than average", "Less than average")
dd2$Att_Car <- as.factor(dd2$Att_Car)
dd3$Att_Car <- as.numeric((dd3$`One-Third` + dd3$CPA)/(dd3$Carries)*100)
dd3$Att_Car <- ifelse(dd3$Att_Car>5.3, "More than average", "Less than average")
dd3$Att_Car <- as.factor(dd3$Att_Car)
dd4$Att_Car <- as.numeric((dd4$`One-Third` + dd4$CPA)/(dd4$Carries)*100)
dd4$Att_Car <- ifelse(dd4$Att_Car>5.3, "More than average", "Less than average")
dd4$Att_Car <- as.factor(dd4$Att_Car)
dd5$Att_Car <- as.numeric((dd5$`One-Third` + dd5$CPA)/(dd5$Carries)*100)
dd5$Att_Car <- ifelse(dd5$Att_Car>5.3, "More than average", "Less than average")
dd5$Att_Car <- as.factor(dd5$Att_Car)

df_3 <- as.data.frame(rbind(dd1,dd2,dd3,dd4,dd5))


```

```{r}

# Splitting data into train and test data
split_3 <- sample.split(df_3, SplitRatio = 0.9)
train_cl_3 <- df_3[split_3 == "TRUE"]
test_cl_3 <- subset(df_3, split_3 == "FALSE")

```

```{r}

#Implementing DT

model_3 <- rpart(Att_Car ~. , data = train_cl_3)

```


```{r}

#Making Predictions

pr_3 <- predict(model_3, newdata = train_cl_3, type="class")

```


```{r}

#Confusion Matrix and Accuracy

confusionMatrix(table(pred = pr_3, true = train_cl_3$Att_Car))

```

```{r}

#Visualizations

pruned_tree_3 <- prune.rpart(model_3, cp=0)

#plot the pruned tree

prp(pruned_tree_3, faclen=0, extra=1,digits=5)

```

```{r}

#Better Viz

rpart.plot(model_3, box.palette="RdGn", shadow.col="gray", nn=TRUE)

```


